language: node_js

sudo: required

services:
    - docker

branches:
  only:
    - master

after_success:
    - docker login -u "liwonace" -p "liwonace!@#"
    - docker build -t liwonace/lhms /root/lhms/.
    - docker push docker.io/liwonace/lhms:latest

script: npm -v
